services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "1"
      SA_PASSWORD: "numsey#2021"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - C:\Users\eduardo.azevedo\Documents\volumes\mssql\mssql_data:/var/opt/mssql/data
  rabbitmq:
    image: rabbitmq:3-management
    environment:
        RABBITMQ_DEFAULT_USER: "admin"
        RABBITMQ_DEFAULT_PASS: "Admin123!"
    ports:
        - "5672:5672"
        - "15672:15672"
  ravendb: 
    image: ravendb/ravendb:latest
    environment:
        RAVEN_Setup_Mode: "None"
        RAVEN_License_Eula_Accepted: "true"
        RAVEN_ServerUrl: "https://0.0.0.0"
        RAVEN_PublicServerUrl: "https://localhost"
        RAVEN_ServerUrl_Tcp: "tcp://0.0.0.0:38888"
        RAVEN_PublicServerUrl_Tcp: "tcp://localhost:38888"
        RAVEN_Security.Certificate.Path: "/certs/my-test.instance.pfx"
        RAVEN_License: "{\"Id\":\"210dc380-84d3-40a4-9a50-a4a731153131\",\"Name\":\"Eduardo Lozano\",\"Keys\":[\"vGwChKZdZtTz3ZSSI/EcgGNYr\",\"hQPSHdnDa+G0/xAKEsw+v2DH7\",\"8yN8Z350nrQdLHItqBxPI2cT3\",\"Rmi+FuGNHvY26qRCSBbTKpaww\",\"3UHcVNG4NPd/2tJouWnVIHfN9\",\"rt2LPZeUjkunidmuM56QgNEm9\",\"I3MqlNjHWsbXzKDfgc5ARAAYE\",\"DNi4wBQYHKEkDCgsMDQ4PEBES\",\"ExQ1FhcYGRobHB0enwIfAJ8CI\",\"ACfAiEgnwIjAJ8CJACfAiUAnw\",\"ImAJ8CJwCfAigAnwIpAJ8CKgCfAisAnwIsAJ8CLQCfAi4AnwIvAJ8CMACfAzFAAp8DMkACnwMzQC2fAzRAJJ8DNUAknwM2QAGfAztAA58DPEAPnwM9QAGfAz5ABZ8DP0ABnwNAQAVDBkQDYo5a\"]}"
    volumes:
        - C:\Users\eduardo.azevedo\Documents\volumes\ravendb\data:/var/lib/ravendb/data
        - C:\Users\eduardo.azevedo\Documents\volumes\ravendb\certs:/certs
    ports:
        - "443:443"
        - "38888:38888"